config/routes.rb
Rails.application.routes.draw do
  
get '/contacts/favourites' => 'contacts#favourites'

resources :contacts, only: [:new, :create, :index, :show, :destroy]

patch '/contacts/:id' => 'contacts#favourite'



end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)
		if @contact.valid?
			@contact.save
			redirect_to contacts_path
		else
			render :new
		end
	end

	def index
		@contacts = Contact.order(name: :asc)
	end

	def show
		@contact = Contact.find(params[:id])
	end

	def destroy
		Contact.find(params[:id]).destroy
		redirect_to contacts_path
	end

	def favourite
		@contact = Contact.find(params[:id])
		if @contact.status
			@contact.update_attributes(status: false)
		else
			@contact.update_attributes(status: true)
		end
		render :show
	end

	def favourites
		@contacts = Contact.where(status: true)
		render :index
	end


	private

	def contact_params
		params.require(:contact).permit(:name, :address, :phone1, :phone2, :email1, :email2)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/favourites.html.erb
<h5> Favourites </h5>

<% @contacts.each do |contact| %>
<p>Name: <%= link_to contact.name, contact_path(contact.id) %></p>
<p>Address: <%= contact.address %></p>
<p>Email: <%= contact.email1 %></p>
<% end %>

app/views/contacts/index.html.erb
<h5> All Contacts </h5>

<% @contacts.each do |contact| %>
  <p>Name: <%= link_to contact.name, contact_path(contact.id) %></p>
  <p>Address: <%= contact.address %> </p>
  <p>Phone1: <%= contact.phone1 %> </p>
<% end %>

app/views/contacts/new.html.erb
<h5> Create a contact </h5>

<%= form_for(@contact) do |f| %>

    <%= f.label :name %>
    <%=f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :phone1 %>
    <%= f.telephone_field :phone1 %>

    <%= f.label :phone2 %>
    <%= f.telephone_field :phone2 %>

    <%= f.label :email1 %>
    <%= f.email_field :email1 %>

    <%= f.label :email2 %>
    <%= f.email_field :email2 %>

    <%= f.submit "Submit" %>
<% end %>

app/views/contacts/show.html.erb
<h5> All Contacts </h5>

<p>Name: <%= @contact.name %> </p>
<p><%= @contact.address %> </p>
<%= @contact.phone1 %>
<%= @contact.phone2 %>
<%= @contact.email1 %>
<%= @contact.email2 %>

<% if @contact.status %>
<p>FAV</p>
<% end %>

<%= link_to "Delete Contact", contact_path(@contact.id), method: "delete" %>
<%= link_to "Favourite", contact_path(@contact.id), method: "patch" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addressbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> Address Book </h1>
<hr/>
<%= yield %>
<hr/>
<%= link_to "All Contacts", contacts_path %>
<%= link_to "Create Contact", new_contact_path %>
<%= link_to "Favourites", contacts_favourites_path %>
</body>
</html>